/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tr_com_serkanozal_jillegal_util_MemoryUtil */

#ifndef _Included_tr_com_serkanozal_jillegal_util_MemoryUtil
#define _Included_tr_com_serkanozal_jillegal_util_MemoryUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tr_com_serkanozal_jillegal_util_MemoryUtil
 * Method:    pinClass
 * Signature: (Ljava/lang/String;)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_tr_com_serkanozal_jillegal_util_MemoryUtil_pinClass
  (JNIEnv *, jclass, jstring);
JNIEXPORT jobject JNICALL Java_tr_com_serkanozal_jillegal_util_MemoryUtil_pinObject
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
